CREATE TABLE raw_material (
    id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(255) NOT NULL,
    stock_qty   NUMBER(19,0) NOT NULL
);

CREATE TABLE product (
    id      NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR2(255) NOT NULL,
    price   NUMBER(19,2) NOT NULL
);

CREATE TABLE product_ingredient (
    id              NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      NUMBER(19,0) NOT NULL,
    raw_material_id NUMBER(19,0) NOT NULL,
    quantity        NUMBER(19,0) NOT NULL,

    CONSTRAINT fk_pi_product      FOREIGN KEY (product_id)      REFERENCES product(id),
    CONSTRAINT fk_pi_raw_material FOREIGN KEY (raw_material_id) REFERENCES raw_material(id)
);